version: "3"
services:
  # https://hub.docker.com/_/mongo/
  db:
    image: mongo:3.4.4
    command: --auth
    volumes:
      - ./config/mongo/data/db:/data/db
    ports:
      - 27017:27017
    tty: true
    container_name: db

  # https://hub.docker.com/_/redis/
  mem:
    image: redis:3.2.8-alpine
    ports:
     - 6379:6379
    tty: true
    container_name: mem

  # https://hub.docker.com/_/node/
  app:
    build: .
    # environment:
      # - MONGO_HOST=${db}
      # - MONGO_HOST2=${MONGO_PATH2}
      # - MONGO_URL=mongodb://mongo:27017/app_development
      # - MONGO_URL2=mongodb://db:27017/app_development

    ports:
      - 3000:3000
    links:
      - db
      - mem
    # depends_on:
    #   - db
    #   - mem
    tty: true
    labels:
    - "videoaulas app in production mode"
    container_name: app
    read_only: false
    volumes: 
      - ./dist:/app/dist
      - ./dist-server:/app/dist-server
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./bin:/app/bin
      - ./config:/app/config

  # https://hub.docker.com/_/nginx/
  web:
    image: nginx:1.13.0-alpine
    ports:
      - 80:80
      - 443:443
    read_only: false
    volumes:
      - ./config/deploy/ssl:/var/ssl
      - ./:/var/www
      - ./config/deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./config/deploy/default:/etc/nginx/sites-enabled/default
    links:
      - app
    tty: true
    container_name: web
