export const CHANGE_USER = 'CHANGE_USER'
export const PROCESS_FORM = 'PROCESS_FORM'
export const LOCATION_CHANGE = 'LOCATION_CHANGE'
export const ON_ENTER_HOOK = 'ON_ENTER_HOOK'
export const INFO = 'INFO'
