export const CHANGE_USER = 'CHANGE_USER'
export const PROCESS_FORM = 'PROCESS_FORM'

export const CHANGE_USER_SIGNUP_HOME = 'CHANGE_USER_SIGNUP_HOME'
export const PROCESS_FORM_SIGNUP_HOME = 'PROCESS_FORM_SIGNUP_HOME'

export const LOCATION_CHANGE = 'LOCATION_CHANGE'

export const CHANGE_CAPTCHA = 'CHANGE_CAPTCHA'
export const ON_ENTER_HOOK = 'ON_ENTER_HOOK'
export const INFO = 'INFO'
